build:
  environment:
    php:
      version: '8.1.2'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit tests --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: clover